### PR TITLE
1jc Create Header.js reference issue #122 changes to UI with text block changes

### PR DESCRIPTION
**Pull request by 1jc**
1jc Create Header.js reference issue #122 changes to UI with text block changes

### CODE REVIEW

**Comment by zenwattage** [comment]
lgtm!

**Comment by 1jc** [comment]
@zenwattage is this okay to merge 1jc

**Comment by zenwattage** [comment]
Yep, looks like it!

**Review by zenwattage — APPROVED** [review]

**Comment by 1jc** [comment]
1jc to merge due to approval

**Pull request merged**
