### PR TITLE
1jc Update Decryption.js reference issue #122 changes to UI with text block changes for css

### PR DESCRIPTION
**Pull request by 1jc**
1jc update Decryption.js reference issue #122 changes to UI with text block changes for css

### CODE REVIEW

**Review by zenwattage — CHANGES_REQUESTED** [review]
Lines 14, and 37 aren't needed, and you are removing formatting which will cause unnecessary merge conflicts and create work.

**Comment by 1jc** [comment]
1jc made changes requested by @zenwattage need approval

**Review by zenwattage — APPROVED** [review]
gtg!

**Comment by 1jc** [comment]
1jc merge pull

**Pull request merged**
