### PR TITLE
updating readme with install/run instructions

### PR DESCRIPTION
**Pull request by zenwattage**
Adding install and run command instructions.

Closes Issue#130

### CODE REVIEW

**Review by 1jc — APPROVED** [review]

**Comment by 1jc** [comment]
1jc reviewed documentation for npm install & run instructions Feb 17 7:21pm

**Comment by kdpcapstone** [comment]
Hey Scott,
Maybe you could add a few more comments to it, like cloning the main repository from github, make sure to git checkout -b branchname so changes aren't accidentally made to main, and npm install axios, and press ctrl-c to stop npm?

**Review by kdpcapstone — COMMENTED** [review]
Hey Scott,
Maybe you could add a few more comments to it, like cloning the main repository from github, make sure to git checkout -b branchname so changes aren't accidentally made to main, and npm install axios, and press ctrl-c to stop npm?

**Comment by zenwattage** [comment]
You only need to install axios on your own as of now as it's not in the package.json in the project. That won't be the case once this is finished.

**Review by kdpcapstone — APPROVED** [review]

**Pull request merged**
