### PR TITLE
1jc for issue #95 UI integration1jc have User story for UI and add code for UI integration

### PR DESCRIPTION
**Pull request by 1jc**
1jc for issue #95 UI integration   reference issue #95

https://github.com/kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely/issues/95

### CODE REVIEW

**Comment by 1jc** [comment]
CI not working per Kyle Bastein feb 9 when pull was initiated

**Comment by zenwattage** [comment]
Made recommendations for integration this code into existing files instead of duplicating/renaming files.

**Review by zenwattage — CHANGES_REQUESTED** [review]
Per Slack Call we recommended integrating these into the existing files.

**Comment by 1jc** [comment]
1jc See issue https://github.com/kdanedesigns/kdpcapstone-AD440-2023-EasilySendDataSecurely/issues/122 to make updated changes for text block

**Pull request closed without merging**
